CREATE TABLE ResourceGroup(
	ResourceGroupId VARCHAR(255) PRIMARY KEY NOT NULL,
	ResourceGroupName VARCHAR(255) NOT NULL,
);

CREATE TABLE Tag(
	TagId VARCHAR(255) PRIMARY KEY NOT NULL,
	TagName VARCHAR(255) NOT NULL
);

CREATE TABLE ResourceGroupTag(
	ResourceGroupId VARCHAR(255) FOREIGN KEY REFERENCES ResourceGroup(ResourceGroupId) ON DELETE CASCADE ON UPDATE CASCADE,
	TagId VARCHAR(255) FOREIGN KEY REFERENCES Tag(TagId) ON DELETE CASCADE ON UPDATE CASCADE
	PRIMARY KEY (ResourceGroupId, TagId)
);